In [52]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.0.3-py3-none-any.whl (149 kB)
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.3

# Installed Capacity per Production Type

In [1]:
import pandas as pd

from datetime import timedelta
from entsoe import EntsoePandasClient
from IPython.core.display import HTML

In [2]:
client = EntsoePandasClient(api_key="24cce779-5703-422f-91b0-b5c9e860e1db")

start = pd.Timestamp('20000101', tz='Europe/Brussels')
end = pd.Timestamp('20200102', tz='Europe/Brussels')

country_code = ['AL', 'AT', 'BE', 'BA', 'BG', 'HR', 'CY', 'CZ', 'DK',
               'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT',
               'LV', 'LT', 'LU', 'ME', 'NL', 'MK', 'NO', 'PL',
               'PT', 'RO', 'RS', 'SK', 'SI', 'ES', 'SE', 'CH', 'UA',
               'UK']

#out : GE, XK

In [124]:
df = pd.DataFrame()


for count, value in enumerate(country_code) :
    temp_df = client.query_installed_generation_capacity(value, start=start,end=end, psr_type=None)
    temp_df.insert(0, 'Country', value)
    df = pd.concat([df, temp_df])
    print(value)
    temp_df = pd.DataFrame()

AL
AT
BE
BA
BG
HR
CY
CZ
DK
EE
FI
FR
DE
GR
HU
IE
IT
LV
LT
LU
ME
NL
MK
NO
PL
PT
RO
RS
SK
SI
ES
SE
CH
UA
UK

# Actual generation per production type

In [6]:
df = pd.DataFrame()

start = pd.Timestamp('20150101', tz='Europe/Brussels')
end = pd.Timestamp('20200101', tz='Europe/Brussels')

country_code = ['AT', 'FR', 'DE', 'UK', 'LU', 'RO']

for count, value in enumerate(country_code) :
    temp_df = client.query_generation(value, start=start,end=end, psr_type=None)
    temp_df.insert(0, 'Country', value)
    df = pd.concat([df, temp_df])
    print(value)
    temp_df = pd.DataFrame()

AT
FR
DE
UK

ValueError: no types given

In [9]:
df

                          Country           Biomass                     \
                                  Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00      AT             304.0                0.0
2015-01-01 00:15:00+01:00      AT             304.0                0.0
2015-01-01 00:30:00+01:00      AT             304.0                0.0
2015-01-01 00:45:00+01:00      AT             304.0                0.0
2015-01-01 01:00:00+01:00      AT             304.0                0.0
...                           ...               ...                ...
2019-12-31 20:30:00+00:00      UK            3018.0                NaN
2019-12-31 21:00:00+00:00      UK            3018.0                NaN
2019-12-31 21:30:00+00:00      UK            3015.0                NaN
2019-12-31 22:00:00+00:00      UK            3012.0                NaN
2019-12-31 22:30:00+00:00      UK            2830.0                NaN

                                 Fossil Gas                     \
                          Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00            1029.0                0.0
2015-01-01 00:15:00+01:00            1019.0                0.0
2015-01-01 00:30:00+01:00            1015.0                0.0
2015-01-01 00:45:00+01:00            1014.0                0.0
2015-01-01 01:00:00+01:00             926.0                0.0
...                                     ...                ...
2019-12-31 20:30:00+00:00           12699.0                0.0
2019-12-31 21:00:00+00:00           11988.0                0.0
2019-12-31 21:30:00+00:00           10583.0                0.0
2019-12-31 22:00:00+00:00           10401.0                0.0
2019-12-31 22:30:00+00:00            9933.0                0.0

                           Fossil Hard coal                     \
                          Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00              16.0                0.0
2015-01-01 00:15:00+01:00              16.0                0.0
2015-01-01 00:30:00+01:00              15.0                0.0
2015-01-01 00:45:00+01:00              15.0                0.0
2015-01-01 01:00:00+01:00              14.0                0.0
...                                     ...                ...
2019-12-31 20:30:00+00:00            1578.0                0.0
2019-12-31 21:00:00+00:00            1113.0                0.0
2019-12-31 21:30:00+00:00            1104.0                0.0
2019-12-31 22:00:00+00:00             999.0                0.0
2019-12-31 22:30:00+00:00             913.0                0.0

                                 Fossil Oil                     \
                          Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00               0.0                0.0
2015-01-01 00:15:00+01:00               0.0                0.0
2015-01-01 00:30:00+01:00               0.0                0.0
2015-01-01 00:45:00+01:00               0.0                0.0
2015-01-01 01:00:00+01:00               0.0                0.0
...                                     ...                ...
2019-12-31 20:30:00+00:00               0.0                0.0
2019-12-31 21:00:00+00:00               0.0                0.0
2019-12-31 21:30:00+00:00               0.0                0.0
2019-12-31 22:00:00+00:00               0.0                0.0
2019-12-31 22:30:00+00:00               0.0                0.0

                                 Geothermal  ...      Wind Onshore  \
                          Actual Aggregated  ... Actual Aggregated
2015-01-01 00:00:00+01:00               0.0  ...              63.0
2015-01-01 00:15:00+01:00               0.0  ...              61.0
2015-01-01 00:30:00+01:00               0.0  ...              65.0
2015-01-01 00:45:00+01:00               0.0  ...              71.0
2015-01-01 01:00:00+01:00               0.0  ...              74.0
...                                     ...  ...               ...
2019-12-31 20:30:00+00:00               NaN  ...            3351.0
2019-12-31 21:00:00+00:00               NaN  ...            3494.0
2019-12-31 21:30:00+00:00               NaN  ...            3718.0
2019-12-31 22:00:00+00:00               NaN  ...            3890.0
2019-12-31 22:30:00+00:00               NaN  ...            3677.0

                                                       Nuclear  \
                          Actual Consumption Actual Aggregated
2015-01-01 00:00:00+01:00                0.0               NaN
2015-01-01 00:15:00+01:00                0.0               NaN
2015-01-01 00:30:00+01:00                0.0               NaN
2015-01-01 00:45:00+01:00                0.0               NaN
2015-01-01 01:00:00+01:00                0.0               NaN
...                                      ...               ...
2019-12-31 20:30:00+00:00              193.0            6961.0
2019-12-31 21:00:00+00:00              239.0            6955.0
2019-12-31 21:30:00+00:00              280.0            6969.0
2019-12-31 22:00:00+00:00              307.0            6962.0
2019-12-31 22:30:00+00:00              302.0            6958.0

                          Fossil Brown coal/Lignite                     \
                                  Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00                       NaN                NaN
2015-01-01 00:15:00+01:00                       NaN                NaN
2015-01-01 00:30:00+01:00                       NaN                NaN
2015-01-01 00:45:00+01:00                       NaN                NaN
2015-01-01 01:00:00+01:00                       NaN                NaN
...                                             ...                ...
2019-12-31 20:30:00+00:00                       NaN                NaN
2019-12-31 21:00:00+00:00                       NaN                NaN
2019-12-31 21:30:00+00:00                       NaN                NaN
2019-12-31 22:00:00+00:00                       NaN                NaN
2019-12-31 22:30:00+00:00                       NaN                NaN

                          Fossil Coal-derived gas                     \
                                Actual Aggregated Actual Consumption
2015-01-01 00:00:00+01:00                     NaN                NaN
2015-01-01 00:15:00+01:00                     NaN                NaN
2015-01-01 00:30:00+01:00                     NaN                NaN
2015-01-01 00:45:00+01:00                     NaN                NaN
2015-01-01 01:00:00+01:00                     NaN                NaN
...                                           ...                ...
2019-12-31 20:30:00+00:00                     NaN                NaN
2019-12-31 21:00:00+00:00                     NaN                NaN
2019-12-31 21:30:00+00:00                     NaN                NaN
2019-12-31 22:00:00+00:00                     NaN                NaN
2019-12-31 22:30:00+00:00                     NaN                NaN

                                     Nuclear     Wind Offshore  \
                          Actual Consumption Actual Aggregated
2015-01-01 00:00:00+01:00                NaN               NaN
2015-01-01 00:15:00+01:00                NaN               NaN
2015-01-01 00:30:00+01:00                NaN               NaN
2015-01-01 00:45:00+01:00                NaN               NaN
2015-01-01 01:00:00+01:00                NaN               NaN
...                                      ...               ...
2019-12-31 20:30:00+00:00                NaN            1964.0
2019-12-31 21:00:00+00:00                NaN            1770.0
2019-12-31 21:30:00+00:00                NaN            1816.0
2019-12-31 22:00:00+00:00                NaN            1985.0
2019-12-31 22:30:00+00:00                NaN            2178.0


                          Actual Consumption
2015-01-01 00:00:00+01:00                NaN
2015-01-01 00:15:00+01:00                NaN
2015-01-01 00:30:00+01:00                NaN
2015-01-01 00:45:00+01:00                NaN
2015-01-01 01:00:00+01:00                NaN
...                                      ...
2019-12-31 20:30:00+00:00                NaN
2019-12-31 21:00:00+00:00                NaN
2019-12-31 21:30:00+00:00                NaN
2019-12-31 22:00:00+00:00                NaN
2019-12-31 22:30:00+00:00                NaN

[481852 rows x 35 columns]

In [59]:
df1 = df

In [60]:
df1 = df1.reset_index(level=0)

In [61]:
df1

                            index Country           Biomass  \
                                          Actual Aggregated
0       2015-01-01 00:00:00+01:00      AT             304.0
1       2015-01-01 00:15:00+01:00      AT             304.0
2       2015-01-01 00:30:00+01:00      AT             304.0
3       2015-01-01 00:45:00+01:00      AT             304.0
4       2015-01-01 01:00:00+01:00      AT             304.0
...                           ...     ...               ...
481847  2019-12-31 20:30:00+00:00      UK            3018.0
481848  2019-12-31 21:00:00+00:00      UK            3018.0
481849  2019-12-31 21:30:00+00:00      UK            3015.0
481850  2019-12-31 22:00:00+00:00      UK            3012.0
481851  2019-12-31 22:30:00+00:00      UK            2830.0

                                 Fossil Gas                     \
       Actual Consumption Actual Aggregated Actual Consumption
0                     0.0            1029.0                0.0
1                     0.0            1019.0                0.0
2                     0.0            1015.0                0.0
3                     0.0            1014.0                0.0
4                     0.0             926.0                0.0
...                   ...               ...                ...
481847                NaN           12699.0                0.0
481848                NaN           11988.0                0.0
481849                NaN           10583.0                0.0
481850                NaN           10401.0                0.0
481851                NaN            9933.0                0.0

        Fossil Hard coal                           Fossil Oil  \
       Actual Aggregated Actual Consumption Actual Aggregated
0                   16.0                0.0               0.0
1                   16.0                0.0               0.0
2                   15.0                0.0               0.0
3                   15.0                0.0               0.0
4                   14.0                0.0               0.0
...                  ...                ...               ...
481847            1578.0                0.0               0.0
481848            1113.0                0.0               0.0
481849            1104.0                0.0               0.0
481850             999.0                0.0               0.0
481851             913.0                0.0               0.0

                           ...      Wind Onshore                     \
       Actual Consumption  ... Actual Aggregated Actual Consumption
0                     0.0  ...              63.0                0.0
1                     0.0  ...              61.0                0.0
2                     0.0  ...              65.0                0.0
3                     0.0  ...              71.0                0.0
4                     0.0  ...              74.0                0.0
...                   ...  ...               ...                ...
481847                0.0  ...            3351.0              193.0
481848                0.0  ...            3494.0              239.0
481849                0.0  ...            3718.0              280.0
481850                0.0  ...            3890.0              307.0
481851                0.0  ...            3677.0              302.0

                 Nuclear Fossil Brown coal/Lignite                     \
       Actual Aggregated         Actual Aggregated Actual Consumption
0                    NaN                       NaN                NaN
1                    NaN                       NaN                NaN
2                    NaN                       NaN                NaN
3                    NaN                       NaN                NaN
4                    NaN                       NaN                NaN
...                  ...                       ...                ...
481847            6961.0                       NaN                NaN
481848            6955.0                       NaN                NaN
481849            6969.0                       NaN                NaN
481850            6962.0                       NaN                NaN
481851            6958.0                       NaN                NaN

       Fossil Coal-derived gas                               Nuclear  \
             Actual Aggregated Actual Consumption Actual Consumption
0                          NaN                NaN                NaN
1                          NaN                NaN                NaN
2                          NaN                NaN                NaN
3                          NaN                NaN                NaN
4                          NaN                NaN                NaN
...                        ...                ...                ...
481847                     NaN                NaN                NaN
481848                     NaN                NaN                NaN
481849                     NaN                NaN                NaN
481850                     NaN                NaN                NaN
481851                     NaN                NaN                NaN

           Wind Offshore
       Actual Aggregated Actual Consumption
0                    NaN                NaN
1                    NaN                NaN
2                    NaN                NaN
3                    NaN                NaN
4                    NaN                NaN
...                  ...                ...
481847            1964.0                NaN
481848            1770.0                NaN
481849            1816.0                NaN
481850            1985.0                NaN
481851            2178.0                NaN

[481852 rows x 36 columns]

In [62]:
df1['index']= pd.to_datetime(df1['index'], utc = True)

In [63]:
df1['index'] = df1['index'].dt.tz_localize(None)

In [50]:
df1 = df1.groupby([df1['index'].map(lambda x: "{}/{}/{}".format(x.day, x.month, x.year)), df1['Country']])

In [52]:
df1 = df1.sum()

C:\Users\daabv\AppData\Local\Temp\ipykernel_9044\2422872323.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1 = df1.sum()

In [58]:
df1.index.sort

<bound method Index.sort of MultiIndex([('1/1/2015', 'AT'),
            ('1/1/2015', 'DE'),
            ('1/1/2015', 'FR'),
            ('1/1/2015', 'UK'),
            ('1/1/2016', 'AT'),
            ('1/1/2016', 'DE'),
            ('1/1/2016', 'FR'),
            ('1/1/2016', 'UK'),
            ('1/1/2017', 'AT'),
            ('1/1/2017', 'DE'),
            ...
            ('9/9/2017', 'FR'),
            ('9/9/2017', 'UK'),
            ('9/9/2018', 'AT'),
            ('9/9/2018', 'DE'),
            ('9/9/2018', 'FR'),
            ('9/9/2018', 'UK'),
            ('9/9/2019', 'AT'),
            ('9/9/2019', 'DE'),
            ('9/9/2019', 'FR'),
            ('9/9/2019', 'UK')],
           names=['index', 'Country'], length=7308)>

In [65]:
df1.to_excel("installed_capacity_per_production_type.xlsx")

# Actual generation per generation unit

In [ ]:
df = pd.DataFrame()

start = pd.Timestamp('20190101', tz='Europe/Brussels')
end = pd.Timestamp('20200102', tz='Europe/Brussels')

country_code = ['FR']

for count, value in enumerate(country_code) :
    temp_df = client.query_generation_per_plant(value, start=start,end=end, psr_type=None)
    temp_df.insert(0, 'Country', value)
    df = pd.concat([df, temp_df])
    print(value)
    temp_df = pd.DataFrame()

# Installed capacity per production unit

In [7]:
df = pd.DataFrame()

country_code = ["BE"]


for count, value in enumerate(country_code) :
    temp_df = client.query_installed_generation_capacity_per_unit(value, start=start,end=end, psr_type=None)
    temp_df.insert(0, 'Country', value)
    df = pd.concat([df, temp_df])
    print(value)
    temp_df = pd.DataFrame()

BE

In [8]:
df

,Country,Bidding Zone,Installed Capacity [MW],Name,Production Type,Voltage Connection Level [kV]
22WSAINT-000221B,BE,10YBE----------2,350,SAINT-GHISLAIN STEG,Fossil Gas,150
22WDOELX40000793,BE,10YBE----------2,1038,DOEL 4,Nuclear,380
22WCOOXII000070C,BE,10YBE----------2,690,COO II T,Hydro Pumped Storage,380
22WDROGEN0000863,BE,10YBE----------2,465,DROGENBOS TGV,Fossil Gas,150
22WINESCO000149P,BE,10YBE----------2,133,INESCO WKK,Fossil Gas,150
22WMARCIN000179H,BE,10YBE----------2,405,Marcinelle Energie (Carsid),Fossil Gas,150
22WSCHELD0002261,BE,10YBE----------2,140,Scheldelaan Exxonmobil,Fossil Gas,150
22WTHORNT000237E,BE,10YBE----------2,147.6,Thorntonbank - C-Power - Area NE,Wind Offshore,150
22WDOELX3000078D,BE,10YBE----------2,1006,DOEL 3,Nuclear,380
22WTHORNT000238C,BE,10YBE----------2,177.6,Thorntonbank - C-Power - Area SW,Wind Offshore,150
22WT-POWE000244W,BE,10YBE----------2,419.8,T-power Beringen,Fossil Gas,150
22WCOOXIX000067T,BE,10YBE----------2,474,COO I T,Hydro Pumped Storage,380
22WDOELX1000076X,BE,10YBE----------2,433,DOEL 1,Nuclear,380
22WRODENH000213L,BE,10YBE----------2,268,RODENHUIZE 4,Biomass,150
22WBELWIN0000271,BE,10YBE----------2,171,Belwind Phase 1,Wind Offshore,150
22WHERDER0001288,BE,10YBE----------2,465,HERDERSBRUG STEG,Fossil Gas,150
22WRINGVA000209C,BE,10YBE----------2,357,RINGVAART STEG,Fossil Gas,150
22WDOELX2000077N,BE,10YBE----------2,433,DOEL 2,Nuclear,380
22WZELZAT0002618,BE,10YBE----------2,315,Zelzate 2 Knippegroen,Fossil Gas,150
22WZANDVL000255D,BE,10YBE----------2,384,Zandvliet Power,Fossil Gas,150
22WTIHANG000239G,BE,10YBE----------2,481,TIHANGE 1N,Nuclear,380
22WTIHANG000242R,BE,10YBE----------2,1045.8,TIHANGE 3,Nuclear,380
22WTIHANG000241T,BE,10YBE----------2,1008,TIHANGE 2,Nuclear,380
22WTIHANG000240V,BE,10YBE----------2,481,TIHANGE 1S,Nuclear,380
22WLANGER0001694,BE,10YBE----------2,235,LANGERLO 1,Fossil Hard coal,150
22WNORTHW000187B,BE,10YBE----------2,216,Northwind,Wind Offshore,220
22WAMERCO000010Y,BE,10YBE----------2,451,Amercoeur 1 R TGV,Fossil Gas,150
22WESCH-S0000967,BE,10YBE----------2,376.4,ESCH-SUR-ALZETTE STEG,Fossil Gas,220
22WPLATEX000208N,BE,10YBE----------2,144,PLATE TAILLE T,Hydro Pumped Storage,150
22WLANGER000171H,BE,10YBE----------2,235,LANGERLO 2,Fossil Hard coal,150
22W20161130----Z,BE,10YBE----------2,165,Nobelwind Offshore Windpark,Wind Offshore,220
22W20180628----H,BE,10YBE----------2,308,Rentel Offshore WP,Wind Offshore,220
22W20181005PU--J,BE,10YBE----------2,255,VILVOORDE GT,Fossil Gas,150
22W201806271---D,BE,10YBE----------2,470,EDF Luminus Seraing TGV,Fossil Gas,220
22W201902131---T,BE,10YBE----------2,369.6,Norther Offshore WP,Wind Offshore,220
22W201909111---M,BE,10YBE----------2,219.1,Northwester 2,Wind Offshore,220